### PR TITLE
Adding Two new Shell Programs

### PR DESCRIPTION
**Pull request by Priya378**
Files:
• Basic arithmetic operations.sh
• Comparing two numbers.sh

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Fix the issues mentioned and sign the commits.

**Comment by Priya378** [comment]
Signed DCO

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Fix these:

- Sign commits
- https://github.com/aravindvnair99/Shell/pull/3/checks?check_run_id=397479549

**Comment by Priya378** [comment]
How to fix "read without -r will mangle backslashes"?

**Comment by aravindvnair99** [comment]
> How to fix "read without -r will mangle backslashes"?

@Priya378 Look at this: https://github.com/koalaman/shellcheck/wiki/SC2162

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Sign the commits and you're good to go.

**Comment by Priya378** [comment]
Yeah....just checked the same link

**Comment by Priya378** [comment]
DCO is signed.Codacy is still reviewing

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Priya378 Don't send multiple PR for the same thing. Use a common branch.

**Comment by aravindvnair99** [comment]
Closing as #7 is ahead.

**Comment by Priya378** [comment]
Ok

**Pull request closed without merging**
