### PR TITLE
Moved files

### PR DESCRIPTION
**Pull request by Priya378**
Files:
•Comparing two numbers.sh
•Basic arithmetic operations.sh

### CODE REVIEW

**Comment by aravindvnair99** [comment]
> How to select a relevant .gitignore file for Shell repository? 12 Commit msgs have to be rewritten according to Angular's commit message convention. But how to modify them? Can you send the conventions to be followed?

@Priya378 :
- https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message
- https://www.gitignore.io/

**Review by aravindvnair99 — COMMENTED** [review]
Read through the comments in #6. Same apply here.

**Review by aravindvnair99 — APPROVED** [review]
@Priya378 Will merge for now. Check user input. Make sure only numbers are entered and check for divisibility by zero.

**Comment by Priya378** [comment]
OK! Thank u xD!

**Pull request merged**
