### PR TITLE
 Added jump script

### PR DESCRIPTION
**Pull request by Nuthi-Sriram**

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Fix the three issues.

**Comment by Nuthi-Sriram** [comment]
Which three issues??

**Comment by aravindvnair99** [comment]
> Which three issues??

https://github.com/aravindvnair99/Shell/pull/1/checks?check_run_id=396900480

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Sign the commit

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
- Plagiarism not permitted.
- Write directly executable scripts such as the ones mentioned in the files already present.

**Comment by aravindvnair99** [comment]
Duplicate of #2

**Pull request closed without merging**
