### PR TITLE
Modified files

### PR DESCRIPTION
**Pull request by Priya378**
Files modified (newBranch3):
•Basic arithmetic operations.sh
•Comparing two numbers.sh

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
For `Basic arithmetic operations.sh`, the right way to check is to see if entered characters are not alphabets or symbols and only numbers. Then for division, there should be a separate check for `division by 0`. Because, `addition, subtraction and multiplication with 0` are still possible. Accordingly, a message can be shown saying `Division by 0 isn't defined`.

**Comment by Priya378** [comment]
Yes, but instead of allowing user to input a zero and display a suitable
message for the division case, I am asking the users to just input the
non-zero numbers.

**Comment by Priya378** [comment]
Modified file (Basic arithmetic operations.sh):

#!/bin/bash
#A shell program to perform basic arithmetic operations
echo "Enter any two positive numbers to perform basic arithmetic operation
(a and b)"
read a
while [[ ! "$a" =~ ^[0-9]+$ ]];do
        echo "Please enter only numbers (1st input):"
        read -r a
done
read b
while [[ ! "$b" =~ ^[0-9]+$ ]];do
        echo "Please enter only numbers (2nd input):"
        read -r b
done
echo "Sum is $((a+b))"
if [ "$a" -gt "$b" ]
then
echo "Difference is $((a-b))"
else
echo "Difference is $((b-a))"
fi
echo "Product is $((b*a))"

if [ "$b" -eq 0 ]
then
        echo "Division by 0 isn't definied, a/b  is not possible"
else
        echo "Quotient when a is divided by b is $((a/b))"
fi

if [ "$a" -eq 0 ]
then
        echo "Division by 0 isn't defined, b/a is not possible"
else
        echo "Quotient when b is divided by a is $((b/a))"
fi

**Comment by Priya378** [comment]
It is *operations in first echo statement.

**Pull request closed without merging**
